project:
  type: website

website:
  title: "statCTV"
  navbar:
    left:
      - href: index.qmd
        text: Video Repository
      - href: casestudies.qmd
        text: Case Studies
      - href: resources.qmd
        text: Resource Repository
      - about.qmd
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto