project:
  type: website

website:
  title: "statCTR"
  site-url: https://www.statCTR.com
  google-analytics: "G-FL4BZV7N6M"
  navbar:
    left:
      - href: videos.qmd
        text: Video Repository
      - href: resources.qmd
        text: Resource Repository
      - about.qmd
  page-footer: 
    left: "&copy; Ryan Peterson 2023" 
  repo-url: https://github.com/petersonR/statCTR
  repo-actions: [issue]
  cookie-consent: true 
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto