project:
  type: website

website:
  title: "statCTR"
  google-analytics: "G-FL4BZV7N6M"
  navbar:
    left:
      - href: index.qmd
        text: Video Repository
      - href: resources.qmd
        text: Resource Repository
      - href: casestudies.qmd
        text: Case Studies
      - about.qmd
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto