---
title: "Contributor Code of Conduct"
---

As contributors and maintainers to this repository, we agree to respect other contributors, the maintainers, and potential users of the repository. We will report issues and provide appropriate documentation as appropriate. As participants in this community, we pledge to a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, caste, color, religion, or sexual identity and orientation.

Examples of unacceptable behavior include: use of sexualized language or imagery, and sexual attention or advances of any kind; trolling, insulting or derogatory comments, and personal or political attacks including gaslighting; public or private harassment; publishing or sharing others\' private information without their explicit permission; and other conduct which could reasonably be considered inappropriate in a professional setting.

Project maintainers have the right and responsibility to remove, edit, reject comments, videos, articles, and other contributions that are not aligned to this Code of Conduct. Project maintainers who do not follow the Code of Conduct may be removed from the project team.

Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the repository maintainers.

This Contributor Code of Conduct is adapted from the [Contributor Covenant](https://www.contributor-covenant.org/), version 2.1 available at <https://www.contributor-covenant.org/version/2/1/code_of_conduct.html>.

\
